# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Program.create(name: "Green and Healthy Homes", description: "A comprehensive housing assessment and improvement program", category: "housing", owner_id: 2, address: "84 Leeson Lane, Newton, MA 02459")
Program.create(name: "Pop Up Play", description: "A mobile program that facilitates active learning through unstructured play", category: "child health", owner_id: 2, address: "20 Laconia Rd, Natick, MA 01760")
Program.create(name: "Walking School Bus", description: "This program provides safe and supervised walking routes for children in urban school districts", category: "education", owner_id: 1, address: "1106 Boylston St, Boston, MA 02115")
Program.create(name: "Meals On Wheels", description: "Meals are delivered to homes of those with inconsistent food access and limited transportation options", category: "food assistance", owner_id: 2, address: "5 Dudley Rd, Newton, MA 02459")
Program.create(name: "Riverside Community Care", description: "School, Day, and After School Programs are highly specialized programs for youth who are experiencing behavioral issues or have been diagnosed with a serious mental illness. These are supportive and therapeutic programs designed to help students cope and better integrate into their school and home communities.", category: "child health", owner_id: 2, address: "270 Bridge Street, Dedham MA, 02026")
Program.create(name: "Oak Square YMCA Afterschool", description: "YMCA Infant, Toddler Preschool and After School Programs are about more than looking after kids. It's about nurturing their development by providing a safe place to learn skills and develop relationships that lead to positive behavior, better health and educational achievement. At the Y, we also focus on role-modeling and teaching kids the Y values of caring, honesty, respect, responsibility. We welcome families at all of our Y program sites and encourage you to visit. Holidays, parties, family nights, special programs, field trips are all occasions for families to get involved at the Y.", category: "education", owner_id: 2, address: "615 Washington St, Brighton, MA 02135")
Program.create(name: "Roxbury Tenants of Harvard", description: "Roxbury Tenants of Harvard Association, Inc. (RTH) is a non-profit housing and human service organization that was founded by residents of the neighborhood in 1969.  Our mission is to insure community participation in decision-making, to foster the improvement of housing, recreation and related facilities for the residents of the Mission Hill area of Boston and to improve the social and economic condition of the community.", category: "housing", owner_id: 2, address: "2 New Whitney St, Boston, MA 02115")
Program.create(name: "Community Resources for Justice", description: "The Crime and Justice Institute (CJI), a division of Community Resources for Justice (CRJ), is a non-profit organization working at the local, state, and national level to improve public safety and the delivery of justice.", category: "social justice", owner_id: 2, address: "355 Boylston St Boston, MA 02116")
Program.create(name: "Achievement Network", description: "Achievement Network (ANet) is a nonprofit dedicated to educational equity. We help schools boost student learning with great teaching that’s grounded in standards, informed by data, and built on the successful practices of educators around the country.", category: "education", owner_id: 2, address: "1 Beacon St. Boston, MA 02108")
Program.create(name: "Family Services of the Merrimack Valley", description: "We are a non-profit social service agency engaged in game changing work which helps children and families live their BEST lives.  Our purpose is to drive outcomes, and we do so by nurturing inner strengths, teaching life skills, championing emotional wellness and providing vital community-based resources in the Merrimack Valley.", category: "child welfare", owner_id: 2, address: "430 N Canal St, Lawrence, MA 01840")
Program.create(name: "A Place To Turn", description: "We are committed to providing emergency food and clothing to our neighbors in the Metrowest community. We will serve those in need in an atmosphere of caring and mutual respect.", category: "food assistance", owner_id: 2, address: "99 Hartford St. Natick, MA 01760")
Program.create(name: "The Possible Project", description: "We use entrepreneurship as a framework to close the skills and opportunites gap facing young people with untapped potential.", category: "youth development", owner_id: 2, address: "17 Sellers St. Cambridge, MA 02139")
Program.create(name: "Resilient Coders", description: "Training people of color for high growth careers as software", category: "education", owner_id: 2, address: "50 Milk St. Boston, MA 02109")





Funder.create(title: "Charles Stewart Mott Foundation/Youth Service Alliance", description: "2019 MLK Day of Service Grants ($1,000) are available to youth development organizations, community-based organizations, and schools in order to effectively recruit and engage youth volunteers in meaningful service activities on MLK Day of Service weekend.", url: "https://www.mott.org/news/releases/", category: "social justice")
Funder.create(title: "Liberty Mutual Foundation", description: "Funding Goal: to address housing instability and other services for teens and young adults. This solicitation builds upon the work of the United States Interagency Council on Homelessness, A Way Home America, the Recommendations of the City of Boston Plan, local Continuums of Care and other area alliances working collaboratively to make youth homelessness, rare brief and non-recurring. We have to positively impact the lives of those ages 14-25 years with this funding, by listening to young people and by forming collaborations between and among youth serving organizations. Projects that are developed by more than one agency may be given extra priority in funding decisions.", url: "https://www.libertymutualgroup.com/about-lm/philanthropy/philanthropy/liberty-mutual-foundation",category: "housing")
Funder.create(title: "The Youth Initiative Fund", description: "The Youth Initiative Fund was initiated seven years ago by the Division of International
Protection in Geneva to support community based protection projects imagined, designed and
led by young people. Since 2014, the YIF has supported more than 100 youth led projects
globally that have addressed protection challenges including sexual and gender-based
violence, peaceful coexistence, child protection and psychosocial wellbeing. The maximum grant is $10,000.", url: "http://unkt.org/2018/10/11/unhcr-call-proposals-youth-initiative-fund/", category: "youth development")
Funder.create(title: "Resist", description: "Supports people's movements for justice and liberation. Applications are due four times per year. Grants range from $1,000 to $4,000", url: "https://resist.org/grants/programs", category: "social justice")
Funder.create(title: "World Bank/Wharton School", description: "Today’s youth will be responsible for implementing the 2030 Agenda and Sustainable Development Goals, approved by the UN in September 2015. UN member states have endorsed a financing for development action agenda, outlining action areas and commitments for the international community. Youth engagement and innovation will be critical for success. The Ideas for Action competition engages young people from around the world to encourage them to develop and share their ideas for financing solutions to deliver the SDGs", url: "http://www.ideas4action.org/2019-ideas-for-action-guidelines/", category: "youth development")

Funder.create(title: "National Parks Service", description: "Save America's Treasures grants from the Historic Preservation Fund provide preservation and/or conservation assistance to nationally significant historic properties and collections. These grants are administered by the National Park Service in partnership with the National Endowment for the Arts, the National Endowment for the Humanities, and the Institute of Museum and Library Services. Grants range from $25,000 to $500,000 and require a dollar-for-dollar match.", url: "https://www.grants.gov/web/grants/view-opportunity.html", category: "environmental")
Funder.create(title: "Santander Bank, Charitable Contributions Program", description: "Our communities are stronger when we invest in each other. That's why the Santander Bank, N.A. Charitable Contributions Program makes donations to charitable organizations in the neighborhoods where our customers and colleagues live and work. We partner with programs that make a measurable difference in the lives of low- and moderate-income individuals and communities.", url: "https://www.santanderbank.com/us/about/charitable-contributions-program", category: "housing")
Funder.create(title: "The MAP Fund", description: "The MAP Fund invests in artistic production as the critical foundation of imagining — and ultimately co-creating — a more equitable and vibrant society. MAP supports original live performance projects that embody a spirit of deep inquiry, particularly works created by artists who question, disrupt, complicate, and challenge inherited notions of social and cultural hierarchy across the United States.", url: "https://mapfundblog.org/", category: "social justice")
Funder.create(title: "WayOUT", description: "Through investing in organizations that provide life-saving services, wayOUT will change what it means to grow up as a gender or sexual minority in America.", url: "https://www.wayout.lgbt/", category: "youth development")
Funder.create(title: "The Boston Foundation", description: "In partnership with our donors, we support nonprofit organizations and act as a convener and civic leader.", url: "https://www.tbf.org/what-we-do/strategic-focus-areas/housing", category: "housing")
Funder.create(title: "National Institute of Health", description: "This funding opporutnity announcement seeks to support research that examines how health information technology adoption impacts minority health and health disparity populations in access to care, quality of care, patient engagement, and health outcomes.", url: "https://grants.nih.gov/grants/guide/pa-files/PAR-19-093.html", category: "health")
